### ISSUE TITLE
Why we need to get queueunit in ErrorFunc?

### ISSUE THREAD

**Issue by KunWuLuan** [kube-queue/kube-queue#57]
When queueunit dequeue failed, kube-queue will get the latest queueunit from apiserver as the following:

https://github.com/kube-queue/kube-queue/blob/main/pkg/scheduler/scheduler.go#L118
newQueueUnit, err := s.QueueClient.SchedulingV1alpha1().QueueUnits(queueUnit.Unit.Namespace).Get(ctx, queueUnit.Unit.Name, v1.GetOptions{})

Sometimes this will cause high latency when qu dequeue failed. Event handler will update queueunitinfo when update event happended(https://github.com/kube-queue/kube-queue/blob/b9bbeb9854f16b8b37e8ec4a80444ed0aaf60cec/pkg/queue/schedulingqueue/priority_scheduling_queue.go#L147). Is this a necessary request for error func?

**Comment by denkensk** [comment]
> Sometimes this will cause high latency when qu dequeue failed.

What the latency means?  the latency for connectting to api-server?

> Event handler will update queueunitinfo when update event happended.

I think maybe we can add some filter in the event-handler to filter some useless update event?

**Comment by KunWuLuan** [comment]
> What the latency means? the latency for connectting to api-server?

Yes, I think so. Sometimes I find 200ms between `filter status 2` and `schedule end`
```
I1129 09:43:22.137503       1 scheduler.go:78] filter status 2 xxx
I1129 09:43:22.342947       1 scheduler.go:98] ---schedule end xxx ---
```

> I think maybe we can add some filter in the event-handler to filter some useless update event?

Event-handler won't cost much resources I think.

**Comment by KunWuLuan** [comment]
Thanks for your reply :).

**Comment by KunWuLuan** [comment]
> > What the latency means? the latency for connectting to api-server?
> 
> Yes, I think so. Sometimes I find 200ms between `filter status 2` and `schedule end`
> 
> ```
> I1129 09:43:22.137503       1 scheduler.go:78] filter status 2 xxx
> I1129 09:43:22.342947       1 scheduler.go:98] ---schedule end xxx ---
> ```
> 
> > I think maybe we can add some filter in the event-handler to filter some useless update event?
> 
> Event-handler won't cost much resources I think.

I found the reason, the default qps is 5 in kube-queue. So we face the long latency when using client to get and update queueunit.
